package hk.hku.flight;

public interface Constant {
    String FLAG_CONNECTION_CHANGE = "FLAG_CONNECTION_CHANGE";
    String FLAG_UP_SIGNAL_QUANTITY = "FLAG_UP_SIGNAL_QUANTITY";
    String FLAG_DOWN_SIGNAL_QUANTITY = "FLAG_DOWN_SIGNAL_QUANTITY";
    String FLAG_BATTERY_PERCENTAGE = "FLAG_BATTERY_PERCENTAGE";
}
